##
# (c) 2021-2025
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
release:
- ./*

size-XS:
- any: [ '*-version.tfvars' ]

size-S:
- any: [ '*-module.tf' ]

size-XL:
- any: [ '**/*.tf', '!*-version.tfvars', '!*-module.tf' ]