##
# (c) 2021-2026
#     Cloud Ops Works LLC - https://cloudops.works/
#     Find us on:
#       GitHub: https://github.com/cloudopsworks
#       WebSite: https://cloudops.works
#     Distributed Under Apache v2.0 License
#
name: Slash command on Cancel/Rollback
on:
  repository_dispatch:
    types:
      - cancel-command
      - rollback-command
      - reject-command
      - close-command

concurrency:
  group: cancel-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  issues: write
  contents: write
  packages: read
  statuses: write
  pull-requests: write

jobs:
  close-pull:
    name: Cancel Rollback Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Closes the Pull Request
        uses: actions/github-script@v8
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.client_payload.slash_command.args.named.pull_request_number }}
          CANCEL_ACTOR: ${{ github.actor }}
          ACTION_EVENT_NAME: ${{ github.event_name }}
          ACTION_TF_PATH: ${{ env.tf_actions_working_dir }}
          ACTION_WORKFLOW: ${{ github.workflow }}
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const pull_request_number = '' + (process.env.PULL_REQUEST_NUMBER || '') + '';
            const cancelActor = '' + (process.env.CANCEL_ACTOR || '') + '';
            const actionEventName = '' + (process.env.ACTION_EVENT_NAME || '') + '';
            const actionTfPath = '' + (process.env.ACTION_TF_PATH || '') + '';
            const actionWorkflow = '' + (process.env.ACTION_WORKFLOW || '') + '';

            const output = `##Cancel was requested
            Cancel/Rollback requested, Pull Request will close now!
            
            *Pusher: @${cancelActor}, Action: \`${actionEventName}\`, Working Directory: \`${actionTfPath}\`, Workflow: \`${actionWorkflow}\`*`;

            const {data: thePull} = await github.rest.pulls.get({
              pull_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            github.rest.issues.createComment({
              issue_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

            github.rest.pulls.update({
              pull_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
            });
